[package]
name = "light-client-poc"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = { version = "1.0", features = ["arbitrary_precision"] }
zkevm-circuits = { path = "../zkevm-circuits", features=["test-circuits"]}
halo2_proofs = { git = "https://github.com/privacy-scaling-explorations/halo2.git", tag = "v0.3.0" }
eyre = { version  = "0.6.8" }
hex = "0.4.3"
num_enum = "0.6.1"
reqwest = "0.11.18"
tokio = { version= "1.28.2", features = ["macros", "rt-multi-thread"]  }
mpt-witness-generator = { path = "../mpt-witness-generator/rustlib" }
ethers = { version = "=2.0.10", features = ["abigen", "rustls", "ws", "ethers-solc"] }
eth-types = { path = "../eth-types" }
gadgets = { path = "../gadgets" }
rand_chacha = "0.3.1"
rand = "0.8.5"
ark-std = "0.4.0"
env_logger = "0.9"
ahash = "=0.8.6"

[dev-dependencies]
ctor = "0.1.22"

[features]
disable-keccak = []
