[package]
name = "bus-mapping"
version = "0.1.0"
edition = "2021"
authors = ["CPerezz <c.perezbaro@gmail.com>"]
license = "MIT OR Apache-2.0"

[dependencies]
axiom-eth = { git = "https://github.com/zemse/axiom-eth", rev = "6bc3fe94", default-features = false, features = ["halo2-pse", "aggregation", "evm"] }
eth-types = { path = "../eth-types" }
gadgets = { path = "../gadgets" }
keccak256 = { path = "../keccak256" }
mock = { path = "../mock", optional = true }

ethers-core = "2.0.6"
ethers-providers = "2.0.6"
halo2_proofs = { git = "https://github.com/privacy-scaling-explorations/halo2.git", tag = "v2023_02_02" }
itertools = "0.10"
lazy_static = "1.4"
log = "0.4.14"
rand = { version = "0.8", optional = true }
serde = {version = "1.0.130", features = ["derive"] }
serde_json = "1.0.66"
strum = "0.24"
strum_macros = "0.24"

revm-precompile = "2.0.2"

[dev-dependencies]
hex = "0.4.3"
pretty_assertions = "1.0.0"
tokio = { version = "1.13", features = ["macros"] }
url = "2.2.2"
mock = { path = "../mock" }
rand = "0.8"

[features]
test = ["mock", "rand"]
