[package]
name = "zkevm-circuits"
version = "0.1.0"
authors = ["therealyingtong <yingtong@z.cash>"]
edition = "2021"
license = "MIT OR Apache-2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
halo2_proofs = { git = "https://github.com/privacy-scaling-explorations/halo2.git", features = ["circuit-params"], tag = "v0.3.0" }
num = "0.4"
sha3 = "0.10"
array-init = "2.0.0"
bus-mapping = { path = "../bus-mapping", default-features = false }
eth-types = { path = "../eth-types" }
gadgets = { path = "../gadgets" }
ethers-core = "=2.0.10"
ethers-signers = { version = "=2.0.10", optional = true }
mock = { path = "../mock", optional = true }
strum = "0.24"
strum_macros = "0.24"
rand_xorshift = "0.3"
rand = "0.8"
itertools = "0.10.3"
lazy_static = "1.4"
log = "0.4"
env_logger = "0.9"
ecdsa = { git = "https://github.com/privacy-scaling-explorations/halo2wrong", tag = "v2024_01_31" }
ecc =       { git = "https://github.com/privacy-scaling-explorations/halo2wrong", tag = "v2024_01_31" }
maingate =  { git = "https://github.com/privacy-scaling-explorations/halo2wrong", tag = "v2024_01_31" }
integer =   { git = "https://github.com/privacy-scaling-explorations/halo2wrong", tag = "v2024_01_31" }
libsecp256k1 = "0.7"
num-bigint = { version = "0.4" }
rand_chacha = "0.3"
snark-verifier = { git = "https://github.com/privacy-scaling-explorations/snark-verifier", tag = "v2024_01_31", default-features = false, features = ["loader_halo2", "system_halo2", "loader_evm"], optional = true }
cli-table = { version = "0.4", optional = true }
num_enum = "0.5.7"
serde = { version = "1.0.130", features = ["derive"] }
serde_json = "1.0.78"
thiserror = "1.0"
hex = {version = "0.4.3", features = ["serde"]}
axiom-eth = { path = "../../axiom-eth/axiom-eth", default-features = false, features = ["halo2-pse", "aggregation", "evm"] }

[target.'cfg(target_arch = "wasm32")'.dependencies]
getrandom = { version = "0.2", features = ["js"] }

[dev-dependencies]
bus-mapping = { path = "../bus-mapping", default-features = false }
ctor = "0.1.22"
ethers-signers = "=2.0.10"
itertools = "0.10.1"
mock = { path = "../mock" }
pretty_assertions = "1.0.0"

[features]
default = ["notwasm"]
notwasm = [ "bus-mapping/notwasm" ]
# We export some test circuits for other crates to consume
test-circuits = []
# Test utilities for testool crate to consume
test-util = ["dep:mock"]
warn-unimplemented = ["eth-types/warn-unimplemented"]
stats = ["warn-unimplemented", "dep:cli-table"]

[[bin]]
name = "stats"
required-features = ["stats"]
